### PR TITLE
Latest version test

### LINKED ISSUE #364: NoClassDefFoundError GroovyPostbuildAction.java, groovy-postbuild:2.3.1 -> groovy-postbuild:2.4
hi,

we recently upgraded the following plugin: **groovy-postbuild:2.3.1 -> groovy-postbuild:2.4**

that leads to the following exception:

`....
href=\"https://jenkins.io/redirect/users-mailing-list\">The users list</a> might be also useful in understanding what has happened.</p><h2>Stack trace</h2><pre style=\"margin:2em; clear:both\">java.lang.NoClassDefFoundError: org/jvnet/hudson/plugins/groovypostbuild/GroovyPostbuildAction\n\tat com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.features.HasBadges.asJson(HasBadges.java:36)\n\tat com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.features.HasBadges.asJson(HasBadges.java:20)\n\tat com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.JobViewSerialiser.serialize(JobViewSerialiser.java:25)\n\tat com.smartcodeltd.jenkinsci.plugins.buildmonitor.viewmodel.JobViewSerialiser.serialize(JobViewSerialiser.java:13)\n\tat ...`

after looking at the source of the plugins the situation looks like this:

- the groovy post build plugin was changed and the GroovyPostbuildAction.java is gone
- the HasBadges.java still relies on the Class (https://github.com/jan-molak/jenkins-build-monitor-plugin/blob/13696d6039fdaaebbc494f22e386ea1773a0db74/build-monitor-plugin/src/main/java/com/smartcodeltd/jenkinsci/plugins/buildmonitor/viewmodel/features/HasBadges.java#L36)
- an alias for xml configs was added (GroovyPostbuildAction.java -> BadgeAction.java), see https://github.com/jenkinsci/groovy-postbuild-plugin/blob/4ac8d3fd88467bc1e4fcf5020b59f1d64475461e/src/main/java/org/jvnet/hudson/plugins/groovypostbuild/GroovyPostbuildDescriptor.java#L93

could you change the code to be compatible with the new version (2.4) of the post build plugin?

our versions: 

- org.jenkins-ci.main:jenkins-war:2.111
- org.jenkins-ci.plugins:build-monitor-plugin:1.12+build.201708172343
- org.jvnet.hudson.plugins:groovy-postbuild:2.4
- org.jenkins-ci.plugins:badge:1.2

cheers and thanks for your efforts
marcel

### PR DESCRIPTION
**Pull request by erikhakansson**
Includes #365 
Closes #364 and #365

### CODE REVIEW

File: build-monitor-acceptance/build-monitor-acceptance-base/src/main/java/net/serenitybdd/integration/jenkins/JenkinsInstance.java [hunk 1]
```diff
@@ -65,8 +65,10 @@ public String pluginUnderTestVersion() {
         return pluginUnderTest.version();
     }
 
+    //todo investigate impact of this
```
Comment (erikhakansson) [inline build-monitor-acceptance/build-monitor-acceptance-base/src/main/java/net/serenitybdd/integration/jenkins/JenkinsInstance.java]: @jan-molak what do you think of this change? I had to do it to make the test run everything for a newer jenkins than the plugin was compiled with.

File: build-monitor-acceptance/build-monitor-acceptance-base/src/test/java/features/ShouldDescribeEachProject.java [hunk 2]
```diff
@@ -47,7 +47,7 @@ public void displaying_a_custom_build_description() throws Exception {
                 Navigate.to(jenkins.url()),
                 HaveAProjectCreated.called("Example Github Project").andConfiguredTo(
                         ExecuteAShellScript.that(outputsGithubProjectLog()),
-                        SetBuildDescription.to("Revision: \\1").basedOnLogLineMatching("Checking out Revision ([^\\s]{6})")
+                        SetBuildDescription.to("Revision: \\1").basedOnLogLineMatching("Checking out Revision ([^\\w]{6})")
```
Comment (erikhakansson) [inline build-monitor-acceptance/build-monitor-acceptance-base/src/test/java/features/ShouldDescribeEachProject.java]: @jan-molak I'm very unsure about this fix, but suddenly I just couldn't get this test to work for any version of Jenkins while it did work before.

And \s is whitespace, right? So it looks like it shouldn't work, but obviously it did before 😄

File: pipeline.groovy [hunk 3]
```diff
@@ -37,9 +37,10 @@ node('hi-speed') {
         }
     }
 
-    archive_artifacts     'build-monitor-plugin/target/*.hpi,pom.xml,build-monitor-plugin/pom.xml,build-monitor-acceptance/pom.xml,build-monitor-acceptance/target/failsafe-reports/*-output.txt'
-    archive_junit_results 'build-monitor-acceptance/target/failsafe-reports/TEST-*.xml'
-    archive_html          'Serenity', 'build-monitor-acceptance/target/site/serenity'
+    archive_artifacts     'build-monitor-plugin/target/*.hpi,pom.xml,build-monitor-plugin/pom.xml,build-monitor-acceptance/pom.xml,build-monitor-acceptance/build-monitor-acceptance-base/pom.xml,build-monitor-acceptance/build-monitor-acceptance-latest/pom.xml,build-monitor-acceptance/build-monitor-acceptance-base/target/failsafe-reports/*-output.txt,build-monitor-acceptance/build-monitor-acceptance-latest/target/failsafe-reports/*-output.txt'
```
Comment (erikhakansson) [inline pipeline.groovy]: @jan-molak Not at all sure about this part, so please correct if wrong :)

File: build-monitor-acceptance/build-monitor-acceptance-base/src/test/java/features/ShouldDescribeEachProject.java (hunk 2 above)
Comment (erikhakansson) [reply build-monitor-acceptance/build-monitor-acceptance-base/src/test/java/features/ShouldDescribeEachProject.java]: oh yeah of course. hmmm this is so weird then. because it won't work for me with ^\\s, but it did before, and it WILL work with ^\\w but it shouldnt.

File: pipeline.groovy (hunk 3 above)
Comment (erikhakansson) [reply pipeline.groovy]: I think I've got a solution for this. I'll get back to you on that.

**Comment by erikhakansson** [comment]
I rebased with latest master and implemented some changes.
Most importantly, I found a way to merge the serenity reports from both acceptance modules. While the fix was simple, it was difficult to find any documentation whatsoever on Serenity and in the end I found the solution in some github issues 😄

**Comment by jan-molak** [comment]
Awesome work, thanks @erikhakansson!

**Comment by jan-molak** [comment]
Looks like [two acceptance tests](https://smartcode-opensource.ci.cloudbees.com/job/build-monitor/Serenity/) will need some tweaking.
I'll try to look into that at some point next week unless you have any capacity to investigate this?
It could be that the OK button needs to be scrolled to or something like that...

**Comment by erikhakansson** [comment]
That's the same test that fails on both 2.46.3 and 2.107.2.

Probably a matter of scrolling as you say, since they don't fail locally. I'll try to just add a scroll and see if that helps. 

Please check #371.

Also, any chance of configuring automatic builds on https://smartcode-opensource.ci.cloudbees.com/ so that PRs are tested automatically? That would easy your job when accepting PRs a lot 😄

**Comment by jan-molak** [comment]
Definitely! When I started with the Build Monitor project Jenkins' support for building PRs was very limited. Things have improved now, so I'll need to look into that :-)
